<?php

namespace Database\Seeders;

use App\Models\Comunidades;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ComunidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $comunidades = [
            ['comunidad' => 'OTRO', 'parroquia' => 'chivacoa'],
            ['comunidad' => '19 DE ABRIL', 'parroquia' => 'chivacoa'],
            ['comunidad' => '19 DE JULIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => '23 DE ENERO', 'parroquia' => 'chivacoa'],
            ['comunidad' => '8 DE MARZO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'AGUA CALIENTE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ALI PRIMERA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ALTO VIENTO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ANDRES BELLO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'BANCO OBRERO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'BARRIO CENTRO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'BARRIO NUEVO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'BICENTENARIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'BRISAS DEL SUR', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CAJA DE AGUA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CALICHE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CEIBAL CENTRO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CEIBAL LAS PALMAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CEIBAL LOS TUBOS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CENTRO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CERRO PRENDIDO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'CHACAO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'COCHINERA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'COMERCIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'UMARIPA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'DANIEL CARIAS LIMA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'DON JUAN CANEPE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL ALGARROBO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL BANO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL BARRADENO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL CALICHE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL CALVARIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL CARLOTANO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL CEIBAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL CEMENTERIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL CONTICINIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL ESTADIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL MANANTIAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL PARAISO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL PERENO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL SAMAN', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL TAMARINDO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL VALLE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL VIGIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL YAGUAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL ZAMURO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL ZANJON', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ELEAZAR LOPEZ CONTRERAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ENMANUEL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EZEQUIEL ZAMORA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'GUAICAIPURO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'GUATANQUIRE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'INDEPENDENCIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'INDIO MACHO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'INDUSTRIAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'JOSE FELIX RIBAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA BARTOLA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA CANDELARIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA CANERIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA CAÑERIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA CEIBA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA COCHINERA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA CUCHILLA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA DIABLERA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA ENCRUCIJADA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA GUANCHERA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA LAGUNITA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA LUCHA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA MONITA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA MONTAÑITA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA MORITA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA PALMA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA PASARELA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA PEDRERA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA PEÑITA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA PEÑA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA TORRE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA VAQUERA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA VIRGEN', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA VIVIENDA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAMBRUSCHINI', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS CARMELITAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS COCUIZAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS COLINAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS COROZAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS DELICIAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS MORITAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS MULITAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS PALMAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LAS VIVIENDAS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LA LIBERTAD', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS CEDROS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS COCOS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS COLORADOS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS COROZOS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS HORCONES', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS MANGUITOS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS PROCERES', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS SILOS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'LOS TUBOS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'MANTECAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'MANUEL VIVE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'MARIA LIONZA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'MONSEÑOR FRANCISCO PRADO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'MONTE OSCURO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'MORROCOYAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'NUEVA ESPERANZA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'NUEVO CIRCO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'PALO VERDE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'PANAMERICANA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'PEGUAIMA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'PIEDRA DE ORO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'POZO NUEVO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'PUEBLO NUEVO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'QUEBRADA MATA CABALLO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'RIVERAS DE CUMARIPA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ROSA INES', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'RUFINO SUAREZ', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SABANA LARGA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SAN ANTONIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SAN ANTONIO DE PEGUAIMA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SAN JOSE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SAN JOSE DE BRUZUAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SAN JOSE DE BUCHICABURE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SAN JUAN', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SAN RAFAEL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SANTA BARBARA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SANTA CATALINA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SANTA EDUVIGIS', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SANTA LUCIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SANTA MARIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SANTA MARIA EL POZON', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SARARE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SIMON BOLIVAR', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SOL DEL ESTE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SORTE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'TIERRA AMARILLA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'TRICENTENARIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'URAPAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'URB  SAN ANTONIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'VALLE VERDE', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'VALLES DE CARAQUITA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'VICENTE LAMBRUSCHINI', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'VICTORIA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'VIRGEN DEL ROSARIO', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'WILLIAM LARA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ZAZARIVACOA', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'ZONA INDUSTRIAL', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL TAMARINDO II', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'GUATANQUIRE I', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'GUATANQUIRE II', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'TAMARINDO 2', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'EL ESTADIUM', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'JOSE FELIX RIBAS 2', 'parroquia' => 'chivacoa'],
            ['comunidad' => 'SANTA EDUVIGES', 'parroquia' => 'chivacoa'],

            // Campo Elias
            ['comunidad' => 'OTRO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'ALTO DEL RIO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'BARRIO NUEVO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'BELLA VISTA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'BRISAS DEL CAMPO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'BUENA VISTA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'CAJA DE AGUA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'CAMPO FLORIDO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'CEMENTERIO VIEJO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'CENTRO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'CENTRO CAMPO ELIAS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'COCUAIMA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL ACEITUNO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL CALLEJON', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL CALVARIO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL CHAMIZO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL COPEY', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL GUACHE', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL MILAGRO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL NARANJAL', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL RODEO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL SAMAN', 'parroquia' => 'campo elias'],
            ['comunidad' => 'EL SILENCIO LOS CERROS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'GUATANQUIRE', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA CANCHA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA CAÑADA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA GRILLERA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA LAGUNA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA MANGA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA PUENTE', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA SABANA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA VILLA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA VIRGEN', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LAS QUISANDAS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LAS VIVIENDAS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LOS CHAMIZOS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LOS COLORADOS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LOS MUERTICOS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LOS NARANJILLOS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LOS VENCEDORES', 'parroquia' => 'campo elias'],
            ['comunidad' => 'MORROCOYAL', 'parroquia' => 'campo elias'],
            ['comunidad' => 'PACUA PACUA', 'parroquia' => 'campo elias'],
            ['comunidad' => '3 PALO GRANDE', 'parroquia' => 'campo elias'],
            ['comunidad' => 'POA POA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'PUEBLO VIEJO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SABANA DE LA ORCA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SAMAN LA CARRETERA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SAN IGNACIO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SAN RAMON', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SANTA CATALINA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SANTA EDUVIGIS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SANTA ELENA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'SECTOR GUATANQUIRE', 'parroquia' => 'campo elias'],
            ['comunidad' => 'TETEIBA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'TIBANA ARRIBA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'TIERRITAS BLANCAS', 'parroquia' => 'campo elias'],
            ['comunidad' => 'VILLA EL JULIANERO', 'parroquia' => 'campo elias'],
            ['comunidad' => 'VILLA SANTA CRUZ', 'parroquia' => 'campo elias'],
            ['comunidad' => 'VILLA SANTA EDUVIGES', 'parroquia' => 'campo elias'],
            ['comunidad' => 'VILLA VIEJA', 'parroquia' => 'campo elias'],
            ['comunidad' => 'LA BARTOLA', 'parroquia' => 'campo elias'],
        ];


        foreach ($comunidades as $comunidad) {
            Comunidades::updateOrCreate(
                ['comunidad' => $comunidad['comunidad']],
                $comunidad
            );
        }
    }
}
